import React from "react";
import "./globals.css";
import ClientWrapper from "./ClientWraper";
import { Header } from "@/components/Header";
import { ProductProvider } from "@/contents/SelectProductContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by created next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return(
    <html lang="en">
      <body>
        <ProductProvider>
          <Header/>
          <ClientWrapper>{children}</ClientWrapper>
        </ProductProvider>
      </body>
    </html>
  )
}